First version of README
prime-slam/evolin pull request #14
Opened 2023-03-09 18:01 UTC by kirill-ivanov-a

- [x] first version of README added;
- [x] evaluation documentation and run examples added.

2023-03-09 18:06 UTC, kirill-ivanov-a commented
#5 #12

2023-03-10 16:51 UTC, anastasiia-kornilova requested changes

2023-03-10 16:51 UTC, anastasiia-kornilova commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Smartphone (please complete the following information):**
Not sure that this is applicable, maybe better to make less overhead bug report template

2023-03-10 16:51 UTC, anastasiia-kornilova commented on README.md
> +2. Install `g2opy` as described [here](https://github.com/uoip/g2opy).
We use custom g2o from my repo, not original one

2023-03-10 16:51 UTC, anastasiia-kornilova commented on evaluation/association/classification/README.md
> +python evaluate.py
It seems that you need to add new line separator for every line, will copypasting into terminal work as it is now?

2023-03-11 14:46 UTC, anastasiia-kornilova approved these changes

2023-03-11 14:50 UTC, merged